'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Button } from '@/components/ui/Button';
import { Input, Textarea, Select } from '@/components/ui/Input';
import { SUBJECTS, EDUCATION_LEVELS, WRITING_TONES } from '@/lib/constants';

const sampleAssignment = `# The Impact of Artificial Intelligence on Modern Education

## Introduction

Artificial Intelligence (AI) has emerged as one of the most transformative technologies of the 21st century, fundamentally reshaping various sectors including healthcare, finance, and particularly education. The integration of AI in educational systems represents a paradigm shift in how knowledge is delivered, consumed, and assessed. This assignment explores the multifaceted impact of AI on modern education, examining both its potential benefits and the challenges it presents.

## 1. Personalized Learning

One of the most significant contributions of AI to education is the ability to deliver personalized learning experiences. Traditional classroom settings often follow a one-size-fits-all approach, which fails to accommodate the diverse learning speeds and styles of individual students.

AI-powered adaptive learning platforms analyze student performance data in real-time, identifying knowledge gaps and adjusting content difficulty accordingly. Systems like Carnegie Learning and DreamBox use machine learning algorithms to create individualized learning paths, ensuring each student receives content tailored to their specific needs (Smith & Johnson, 2023).

## 2. Intelligent Tutoring Systems

AI-driven tutoring systems provide students with 24/7 access to academic support. These systems can:

- Answer questions in natural language
- Provide step-by-step problem-solving guidance
- Offer immediate feedback on assignments
- Track progress over time and identify patterns

Research by Zhang et al. (2024) demonstrates that students using AI tutoring systems showed a 23% improvement in learning outcomes compared to traditional methods.

## 3. Automated Assessment

AI has revolutionized the assessment process through:

| Feature | Traditional | AI-Powered |
|---------|------------|------------|
| Grading Speed | Days/Weeks | Seconds |
| Consistency | Variable | Uniform |
| Feedback | Limited | Detailed |
| Scalability | Low | High |

Automated essay scoring systems can now evaluate written work with accuracy comparable to human graders, while providing instant, detailed feedback to students (Brown, 2023).

## 4. Challenges and Concerns

Despite its benefits, AI in education raises several important concerns:

1. **Digital Divide**: Not all students have equal access to AI-powered tools
2. **Data Privacy**: Collection of student data raises ethical questions
3. **Over-reliance**: Risk of students becoming dependent on AI assistance
4. **Bias**: AI systems may perpetuate existing biases in educational content

## Conclusion

AI represents a powerful tool for enhancing educational outcomes when implemented thoughtfully and ethically. The key lies in viewing AI not as a replacement for human educators, but as a complement that enables more effective teaching and learning. As technology continues to evolve, educational institutions must adapt their approaches to harness AI's potential while addressing its limitations.

## References

1. Brown, A. (2023). "Automated Assessment in Higher Education." Journal of Educational Technology, 45(2), 112-128.
2. Smith, R. & Johnson, K. (2023). "Adaptive Learning Systems: A Meta-Analysis." Educational Research Review, 38, 100-115.
3. Zhang, L., Wang, M., & Chen, H. (2024). "AI Tutoring Systems and Student Outcomes." Computers & Education, 198, 104-119.

---
*Word Count: 487 | Generated by StudyGenie AI*`;

export default function AssignmentsPage() {
  const [topic, setTopic] = useState('');
  const [subject, setSubject] = useState('Computer Science');
  const [level, setLevel] = useState('Undergraduate (B.Tech/B.Sc/BA)');
  const [wordCount, setWordCount] = useState('500');
  const [tone, setTone] = useState('Academic & Formal');
  const [additionalInstructions, setAdditionalInstructions] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [result, setResult] = useState('');
  const [showResult, setShowResult] = useState(false);
  const [activeTab, setActiveTab] = useState<'form' | 'result'>('form');

  const handleGenerate = async () => {
    if (!topic.trim()) return;
    setIsGenerating(true);
    setShowResult(false);
    await new Promise((resolve) => setTimeout(resolve, 3000));
    setResult(sampleAssignment);
    setShowResult(true);
    setIsGenerating(false);
    setActiveTab('result');
  };

  return (
    <div>
      {/* Page Header */}
      <motion.div
        initial={{ opacity: 0, y: -10 }}
        animate={{ opacity: 1, y: 0 }}
        className="mb-8"
      >
        <h1 className="text-2xl sm:text-3xl font-bold text-white flex items-center gap-3">
          <span className="text-3xl">✍️</span> AI Assignment Writer
        </h1>
        <p className="text-dark-400 text-sm mt-1">
          Generate human-like assignments with proper citations and formatting
        </p>
      </motion.div>

      {/* Mobile tab switcher */}
      <div className="lg:hidden glass-card !p-1 mb-4">
        <div className="flex gap-1">
          <button
            onClick={() => setActiveTab('form')}
            className={`flex-1 py-2.5 rounded-xl text-sm font-medium transition-all ${
              activeTab === 'form' ? 'bg-brand-500/20 text-white border border-brand-500/30' : 'text-dark-400'
            }`}
          >
            ⚙️ Configure
          </button>
          <button
            onClick={() => setActiveTab('result')}
            className={`flex-1 py-2.5 rounded-xl text-sm font-medium transition-all ${
              activeTab === 'result' ? 'bg-brand-500/20 text-white border border-brand-500/30' : 'text-dark-400'
            }`}
          >
            📄 Result
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-5 gap-6">
        {/* Form Panel */}
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: 0.1 }}
          className={`lg:col-span-2 space-y-4 ${activeTab !== 'form' ? 'hidden lg:block' : ''}`}
        >
          <div className="glass-card !p-6 space-y-5">
            <Input
              label="Topic / Title"
              placeholder="e.g., Impact of AI on Modern Education"
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
            />

            <Select
              label="Subject"
              options={SUBJECTS.map((s) => ({ value: s, label: s }))}
              value={subject}
              onChange={(e) => setSubject(e.target.value)}
            />

            <Select
              label="Education Level"
              options={EDUCATION_LEVELS.map((l) => ({ value: l, label: l }))}
              value={level}
              onChange={(e) => setLevel(e.target.value)}
            />

            <div className="grid grid-cols-2 gap-3">
              <Input
                label="Word Count"
                type="number"
                placeholder="500"
                value={wordCount}
                onChange={(e) => setWordCount(e.target.value)}
              />
              <Select
                label="Writing Tone"
                options={WRITING_TONES.map((t) => ({ value: t, label: t }))}
                value={tone}
                onChange={(e) => setTone(e.target.value)}
              />
            </div>

            <Textarea
              label="Additional Instructions (Optional)"
              placeholder="Any specific requirements, include/exclude topics, citation style..."
              value={additionalInstructions}
              onChange={(e) => setAdditionalInstructions(e.target.value)}
              className="!min-h-[80px]"
            />

            {/* Feature toggles */}
            <div className="space-y-2">
              <p className="text-sm font-medium text-dark-300">Enhancement Options</p>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                {[
                  { label: 'Add Citations', icon: '📚', active: true },
                  { label: 'AI Humanizer', icon: '🤖', active: true },
                  { label: 'Include Tables', icon: '📊', active: false },
                  { label: 'Add Diagrams', icon: '📈', active: false },
                ].map((opt) => (
                  <label
                    key={opt.label}
                    className={`flex items-center gap-2 px-3 py-2 rounded-xl cursor-pointer transition-all ${
                      opt.active ? 'bg-brand-500/10 border border-brand-500/20' : 'bg-white/5 border border-white/5'
                    }`}
                  >
                    <input type="checkbox" defaultChecked={opt.active} className="sr-only" />
                    <span className="text-sm">{opt.icon}</span>
                    <span className="text-xs font-medium text-dark-300">{opt.label}</span>
                    <div className={`ml-auto w-4 h-4 rounded-full border-2 flex items-center justify-center ${
                      opt.active ? 'border-brand-500 bg-brand-500' : 'border-dark-500'
                    }`}>
                      {opt.active && (
                        <svg className="w-2.5 h-2.5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                        </svg>
                      )}
                    </div>
                  </label>
                ))}
              </div>
            </div>

            <Button
              variant="primary"
              size="lg"
              className="w-full"
              onClick={handleGenerate}
              loading={isGenerating}
              disabled={!topic.trim()}
            >
              {isGenerating ? 'Generating Assignment...' : '✍️ Generate Assignment'}
            </Button>
          </div>
        </motion.div>

        {/* Result Panel */}
        <motion.div
          initial={{ opacity: 0, x: 20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: 0.2 }}
          className={`lg:col-span-3 ${activeTab !== 'result' ? 'hidden lg:block' : ''}`}
        >
          <div className="glass-card !p-6 min-h-[600px] relative">
            <AnimatePresence mode="wait">
              {isGenerating ? (
                <motion.div
                  key="loading"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  className="absolute inset-0 flex flex-col items-center justify-center"
                >
                  <div className="w-16 h-16 rounded-2xl bg-purple-500/20 flex items-center justify-center mb-4">
                    <span className="text-3xl animate-bounce-slow">✍️</span>
                  </div>
                  <p className="text-white font-medium">Crafting your assignment...</p>
                  <p className="text-dark-400 text-sm mt-1">Adding research, citations & formatting</p>
                  <div className="mt-6 w-48">
                    <div className="space-y-2">
                      {['Researching topic...', 'Writing content...', 'Adding citations...'].map((step, i) => (
                        <motion.div
                          key={step}
                          initial={{ opacity: 0, x: -10 }}
                          animate={{ opacity: 1, x: 0 }}
                          transition={{ delay: i * 0.8 }}
                          className="flex items-center gap-2 text-xs text-dark-400"
                        >
                          <motion.div
                            animate={{ scale: [1, 1.2, 1] }}
                            transition={{ duration: 1, repeat: Infinity, delay: i * 0.3 }}
                            className="w-1.5 h-1.5 rounded-full bg-brand-500"
                          />
                          {step}
                        </motion.div>
                      ))}
                    </div>
                  </div>
                </motion.div>
              ) : showResult ? (
                <motion.div
                  key="result"
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0 }}
                >
                  {/* Toolbar */}
                  <div className="flex items-center justify-between mb-4 pb-4 border-b border-white/5">
                    <div className="flex items-center gap-2">
                      <span className="text-xs px-2 py-1 rounded-full bg-green-500/10 text-green-400 border border-green-500/20">
                        ✓ Generated
                      </span>
                      <span className="text-xs text-dark-400">487 words</span>
                    </div>
                    <div className="flex gap-2">
                      <button className="text-xs px-3 py-1.5 rounded-lg bg-white/5 text-dark-300 hover:text-white hover:bg-white/10 transition-all">
                        📋 Copy
                      </button>
                      <button className="text-xs px-3 py-1.5 rounded-lg bg-white/5 text-dark-300 hover:text-white hover:bg-white/10 transition-all">
                        📄 PDF
                      </button>
                      <button className="text-xs px-3 py-1.5 rounded-lg bg-white/5 text-dark-300 hover:text-white hover:bg-white/10 transition-all">
                        📝 DOCX
                      </button>
                      <button className="text-xs px-3 py-1.5 rounded-lg bg-brand-500/20 text-brand-300 hover:bg-brand-500/30 transition-all">
                        🔄 Regenerate
                      </button>
                    </div>
                  </div>
                  {/* Content */}
                  <div className="prose prose-invert prose-sm max-w-none overflow-y-auto max-h-[500px] scrollbar-hide">
                    <pre className="whitespace-pre-wrap text-sm text-dark-200 leading-relaxed font-sans">
                      {result}
                    </pre>
                  </div>
                </motion.div>
              ) : (
                <motion.div
                  key="empty"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  className="absolute inset-0 flex flex-col items-center justify-center text-center p-6"
                >
                  <div className="text-5xl mb-4">✍️</div>
                  <p className="text-white font-medium mb-1">Your Assignment Preview</p>
                  <p className="text-dark-400 text-sm max-w-xs">
                    Fill in the details on the left and click Generate to create your AI-powered assignment
                  </p>
                  {/* Templates */}
                  <div className="mt-8 w-full max-w-sm">
                    <p className="text-xs font-medium text-dark-400 mb-3 uppercase tracking-wider">Quick Templates</p>
                    <div className="space-y-2">
                      {[
                        { label: 'Research Paper', icon: '🔬' },
                        { label: 'Essay', icon: '📝' },
                        { label: 'Case Study', icon: '💼' },
                        { label: 'Literature Review', icon: '📚' },
                      ].map((template) => (
                        <button
                          key={template.label}
                          onClick={() => setTopic(`${template.label}: `)}
                          className="w-full flex items-center gap-3 px-4 py-3 rounded-xl bg-white/5 border border-white/5 hover:bg-white/10 hover:border-white/10 transition-all text-left"
                        >
                          <span className="text-lg">{template.icon}</span>
                          <span className="text-sm text-dark-300">{template.label}</span>
                          <svg className="w-4 h-4 text-dark-500 ml-auto" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                          </svg>
                        </button>
                      ))}
                    </div>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
